
platform :ios, '8.0'

workspace 'FastDevFramework'

abstract_target 'FastDev' do
    pod 'KissXML'
    pod 'YogaKit'
    pod 'AFNetworking'
    
    # Has its own copy of ShowsKit + ShowWebAuth
    target 'FastDevDemo' do
        project 'FastDevDemo/FastDevDemo.xcodeproj'
    end
    
    # Has its own copy of ShowsKit + ShowTVAuth
    target 'FastDevFramework' do
        
    end
end
